/*
Even Fibonacci Sum

Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89... By considering the terms in the Fibonacci sequence whose values do not exceed 4 million, find the sum of the even-valued terms.
Concepts: Loops, if statements
Algorithm:


Initialize variables a = 1, b = 2, and sum = 2 (since 2 is even).
Use a while loop that runs as long as the next Fibonacci term (next = a + b) does not exceed 4,000,000.
Inside the loop, use an if statement to check if next is even (next % 2 == 0).
If it is, add it to sum.
Update a = b and b = next. Print sum.
*/

package deloitte.vilt.practice;

public class q2 {
    public static void main(String[] args) {

        int a = 1;
        int b = 2;
        int sum = 2;
        int next = a + b;

        while (next <= 4000000) {

            if (next % 2 == 0) {
                sum += next;
            }
            
            a = b;
            b = next;
            next = a + b;
        }

        System.out.println("Even Fibonacci Sum: " + sum);
    }
}